### PR TITLE
Create testReview-file.txt

### PR DESCRIPTION
**Pull request by prad-j**
Test the protected branch functionality in this file with more scenarios.

### CODE REVIEW

**Review by pramod-dj — COMMENTED** [review]
This is only for comment.
Check if I can merge after that.

**Review by pramod-dj — CHANGES_REQUESTED** [review]
This is for Request Changes
Test if I can merge it after this.

**Review by prad-j — COMMENTED** [review]
Ok this is the comment by the author of the file.

**Review by pramod-dj — COMMENTED** [review]
OK 
I just checked the comment.
I am OK with that.

Adding the link of the comment
https://github.com/prad-j/new-pull/pull/4#pullrequestreview-563176551

**Review by pramod-dj — APPROVED** [review]
Hahaha

Just tested that the author himself cannot approve his own changes.
You need me to approve them.
OK approved

**Pull request merged**
